### ISSUE TITLE
想问一下，搜索的接口是这个吗？

### ISSUE THREAD

**Issue by 1414648814** [ashen-zhao/linjiaMusic#3]
- (void)readSearchData:(NSString *)keyWord {
  NSDictionary *parameDict = [NSDictionary dictionaryWithObjects:@[keyWord, @"1", @"50"] forKeys:@[@"q", @"page", @"size"]];
  
  [NetworkHelper JsonDataWithUrl:@"http://so.ard.iyyin.com/s/song_with_out" success:^(id data) {
      for (NSDictionary *dict in data[@"data"]) {
          MusicModel *model = [MusicModel new];
          [model setValuesForKeysWithDictionary:dict];
          [self.dataSourceArr addObject:model];
      }
      [self.tableView reloadData];
  } fail:^{
  
  } view:self.view parameters:parameDict];
  }

**Comment by 1414648814** [comment]
如果我想搜索一个歌手的歌曲和专辑，应该怎么搜索呢？

**Comment by 1414648814** [comment]
我通过wireshark抓到了，接口网址是
http://search.dongting.com/song/search/old?page=1&q=徐佳莹&size=50

希望后面看到的同学注意～

**Comment by ashen-zhao** [comment]
赞
